#!/bin/bash

# ==============================================================================
# OpenTenBase CREATE FORCE VIEW - Robust Automated Cluster Test Script (v3)
# ==============================================================================
#
# 此脚本将自动完成以下任务:
# 1. 创建一个临时的目录结构来存放所有集群节点的数据。
# 2. 动态生成一个用于单机测试的 pgxc_ctl.conf 配置文件。
# 3. 使用 pgxc_ctl 工具初始化并启动一个完整的最小化集群 (1 GTM, 1 CN, 2 DN)。
# 4. 连接到 Coordinator 节点，执行完整的 FORCE VIEW 功能测试。
# 5. 无论成功或失败，都会自动关闭并清理整个集群和所有数据。
#
# 使用方法:
# 1. 确保已完成 OpenTenBase 的编译和安装。
# 2. 将此脚本放置在任何位置。
# 3. 根据您的实际情况，修改下面的 "配置变量" 部分。
# 4. 在终端中执行: bash test_force_view.sh
#
# ==============================================================================

# --- 配置变量 (请根据您的环境修改) ---

# OpenTenBase 的安装路径 (configure --prefix 指定的路径)
INSTALL_DIR="/opt/opentenbase"

# 用于存放所有节点数据的临时父目录 (脚本会自动创建和删除)
DATA_DIR_BASE="/tmp/opentenbase_cluster_$$" # $$ 确保每次运行路径唯一

# pgxc_ctl 工具需要一个目录来存放其状态文件
PGXC_CTL_DIR="${DATA_DIR_BASE}/pgxc_ctl"

# 集群配置
GTM_PORT=20001
COORD_PORT=25432  # 我们将连接到这个端口进行测试
COORD_POOL_PORT=25433
DN1_PORT=21001
DN1_POOL_PORT=21002
DN2_PORT=22001
DN2_POOL_PORT=22002

# 测试数据库名称
DB_NAME="force_view_test"

# pgxc_ctl 日志文件
PGXC_LOG="${PGXC_CTL_DIR}/pgxc_ctl.log"

# --- 脚本主体 ---

# 函数：打印彩色信息
print_msg() {
    COLOR_GREEN="\033[0;32m"; COLOR_RED="\033[0;31m"; COLOR_YELLOW="\033[0;33m"; COLOR_RESET="\033[0m"
    case "$1" in
        "green") echo -e "${COLOR_GREEN}✔ $2${COLOR_RESET}"; ;;
        "red") echo -e "${COLOR_RED}✘ $2${COLOR_RESET}"; ;;
        "yellow") echo -e "${COLOR_YELLOW}➜ $2${COLOR_RESET}"; ;;
        *) echo -e "$2"; ;;
    esac
}

# 函数：在脚本退出时执行清理
cleanup() {
    print_msg "yellow" "\n[ 正在执行清理... ]"
    if [ -d "$PGXC_CTL_DIR" ]; then
        print_msg "" "正在关闭并清理整个集群..."
        # -c 指定配置文件，stop all 会停止所有节点
        $INSTALL_DIR/bin/pgxc_ctl -c $PGXC_CTL_DIR/pgxc_ctl.conf stop all > /dev/null 2>&1
    fi
    print_msg "" "正在删除所有临时数据和配置目录..."
    rm -rf "$DATA_DIR_BASE"
    print_msg "green" "环境清理完毕。"
}

# 设置 trap，确保无论脚本如何退出（正常结束、出错、被中断），cleanup 函数都会被调用
trap cleanup EXIT

# 函数：动态生成 pgxc_ctl.conf 配置文件
generate_pgxc_config() {
    mkdir -p $PGXC_CTL_DIR
    local conf_file="$PGXC_CTL_DIR/pgxc_ctl.conf"
    local owner=$(whoami)

    cat << EOF > "$conf_file"
# pgxc configuration file
#
# This file is generated by an automated test script.
#
pgxcOwner=$owner
pgxcUser=\$pgxcOwner
pgxcInstallDir="$INSTALL_DIR"

# GTM
gtmName=gtm
gtmMasterServer=localhost
gtmMasterPort=$GTM_PORT
gtmMasterDir="$DATA_DIR_BASE/gtm"
gtmSlave=n
gtmExtraConfig=none
gtmSpecificExtraConfig=none

# Coordinators
coordNames=(cn1)
coordMasterServers=(localhost)
coordPorts=($COORD_PORT)
poolerPorts=($COORD_POOL_PORT)
coordMasterDirs=("$DATA_DIR_BASE/coord")
coordMaxWALsernder=0
coordSlave=n
coordArchLogDirs=("$DATA_DIR_BASE/coord_arch")

# Datanodes
datanodeNames=(dn1 dn2)
datanodeMasterServers=(localhost localhost)
datanodePorts=($DN1_PORT $DN2_PORT)
datanodePoolerPorts=($DN1_POOL_PORT $DN2_POOL_PORT)
datanodeMasterDirs=("$DATA_DIR_BASE/dn1" "$DATA_DIR_BASE/dn2")
dnMaxWALsender=0
datanodeSlave=n
datanodeArchLogDirs=("$DATA_DIR_BASE/dn1_arch" "$DATA_DIR_BASE/dn2_arch")

# --- hba ---
pg_hba_init_value="host all \$pgxcOwner 127.0.0.1/32 trust"
EOF
}

# 函数：执行 SQL 命令并检查结果
run_test() {
    local description="$1"; local sql_command="$2"; local expected_result="$3"; local expected_error_msg="$4"
    printf "  - %-60s" "$description"
    output=$($PSQL_CMD -c "$sql_command" 2>&1); exit_code=$?
    if [ "$expected_result" == "SUCCESS" ]; then
        if [ $exit_code -eq 0 ]; then print_msg "green" "[ PASSED ]"; return 0;
        else
            print_msg "red" "[ FAILED ]"; echo "    错误: 命令意外失败。"; echo "    输出:"; echo "$output" | sed 's/^/    | /'; return 1;
        fi
    elif [ "$expected_result" == "FAIL" ]; then
        if [ $exit_code -ne 0 ]; then
            if [[ -z "$expected_error_msg" || "$output" == *"$expected_error_msg"* ]]; then print_msg "green" "[ PASSED (Expected Fail) ]"; return 0;
            else
                print_msg "red" "[ FAILED ]"; echo "    错误: 命令失败了，但错误信息不符合预期。"; echo "    预期包含: '$expected_error_msg'"; echo "    实际输出:"; echo "$output" | sed 's/^/    | /'; return 1;
            fi
        else
            print_msg "red" "[ FAILED ]"; echo "    错误: 命令意外成功，但预期它会失败。"; return 1;
        fi
    fi
}

# --- 脚本执行开始 ---

# 检查是否以 root 用户运行
if [ "$(whoami)" == "root" ]; then
    print_msg "yellow" "警告: 您正在以 root 用户运行此脚本。pgxc_ctl 可能会产生警告，但这在 Docker 容器中通常是可接受的。"
fi

# 设置 psql 命令路径
PSQL_CMD="$INSTALL_DIR/bin/psql -h localhost -p $COORD_PORT -q -v ON_ERROR_STOP=1 -d postgres"

print_msg "yellow" "开始 CREATE FORCE VIEW 功能自动化测试 (v3 - 集群模式)..."
print_msg "yellow" "日志将输出到: $PGXC_LOG"

# 步骤 1: 准备环境
print_msg "yellow" "\n[ 步骤 1: 准备测试环境 ]"
print_msg "" "正在生成 pgxc_ctl 配置文件..."
generate_pgxc_config
print_msg "" "正在使用 pgxc_ctl 初始化并启动整个集群..."
# 使用 pgxc_ctl init all，它会自动完成所有节点的初始化和启动
$INSTALL_DIR/bin/pgxc_ctl -c $PGXC_CTL_DIR/pgxc_ctl.conf init all > $PGXC_LOG 2>&1
if [ $? -ne 0 ]; then
    print_msg "red" "集群初始化失败！请检查日志 $PGXC_LOG。"; exit 1
fi

# 创建测试数据库
print_msg "" "正在创建测试数据库..."
# 需要连接到 postgres 库来创建新库
$INSTALL_DIR/bin/psql -h localhost -p $COORD_PORT -c "CREATE DATABASE $DB_NAME;" postgres >> $PGXC_LOG 2>&1
PSQL_CMD="$INSTALL_DIR/bin/psql -h localhost -p $COORD_PORT -q -v ON_ERROR_STOP=1 -d $DB_NAME"
print_msg "green" "环境准备完毕，集群正在运行。"

# 步骤 2: 运行测试
print_msg "yellow" "\n[ 步骤 2: 执行测试用例 ]"
(
    # ... 这里是与之前完全相同的测试逻辑 ...
    print_msg "yellow" "\n====== 阶段一: 核心功能测试 (对应需求 1.1) ======"
    run_test "1.1: 创建一个非正常视图" \
        "CREATE FORCE VIEW fv1 (id, name) AS SELECT p_id, p_name FROM non_existent_table;" \
        "SUCCESS"
    
    run_test "1.2: 验证视图已创建 (通过 \\d)" \
        "\\d fv1" \
        "SUCCESS"

    run_test "1.3: 验证视图不可用" \
        "SELECT * FROM fv1;" \
        "FAIL" "does not exist"

    run_test "1.4: 创建依赖表以 '治愈' 视图" \
        "CREATE TABLE non_existent_table (p_id int, p_name text) DISTRIBUTE BY REPLICATION; INSERT INTO non_existent_table VALUES (101, 'Gadget');" \
        "SUCCESS"

    run_test "1.5: 验证视图现在可用" \
        "SELECT * FROM fv1;" \
        "SUCCESS"

    print_msg "yellow" "\n====== 阶段二: 视图替换与生命周期 (需求 1.2 & 1.3) ======"
    run_test "2.1: 创建一个正常的视图作为基础" \
        "CREATE TABLE real_table(id int) DISTRIBUTE BY REPLICATION; CREATE VIEW view_a AS SELECT * FROM real_table;" \
        "SUCCESS"

    run_test "2.2: (正常 -> 非正常) 替换为非正常视图" \
        "CREATE OR REPLACE FORCE VIEW view_a (id) AS SELECT col FROM another_non_existent;" \
        "SUCCESS"
    
    run_test "2.3: 验证替换后的视图不可用" \
        "SELECT * FROM view_a;" \
        "FAIL" "does not exist"

    run_test "2.4: 创建依赖并 (非正常 -> 正常) 替换回正常视图" \
        "CREATE TABLE another_non_existent(col int) DISTRIBUTE BY REPLICATION; CREATE OR REPLACE VIEW view_a AS SELECT * FROM another_non_existent;" \
        "SUCCESS"
    
    run_test "2.5: 验证最终视图可用" \
        "SELECT * FROM view_a;" \
        "SUCCESS"

    print_msg "yellow" "\n====== 阶段三: 依赖关系处理 (需求 1.4) ======"
    run_test "3.1: 创建依赖于不存在的函数的视图" \
        "CREATE FORCE VIEW fv_func AS SELECT non_existent_func(1);" \
        "SUCCESS"
    
    run_test "3.2: 验证视图因函数不存在而不可用" \
        "SELECT * FROM fv_func;" \
        "FAIL" "does not exist"

    run_test "3.3: 创建依赖的函数" \
        "CREATE FUNCTION non_existent_func(a int) RETURNS int AS 'SELECT \$1 * 10' LANGUAGE SQL;" \
        "SUCCESS"

    run_test "3.4: 验证视图现在因函数存在而可用" \
        "SELECT * FROM fv_func;" \
        "SUCCESS"
    
    run_test "3.5: 验证动态依赖已建立 (DROP RESTRICT 应失败)" \
        "DROP FUNCTION non_existent_func(integer);" \
        "FAIL" "depend on it"
        
    run_test "3.6: 验证 CASCADE 可以删除视图和函数" \
        "DROP FUNCTION non_existent_func(integer) CASCADE;" \
        "SUCCESS"

    print_msg "yellow" "\n====== 阶段四: 健壮性与回归测试 ======"
    run_test "4.1: 验证对 SELECT * 的限制" \
        "CREATE FORCE VIEW fv_star AS SELECT * FROM star_table;" \
        "FAIL" "does not support \"*\""
    
    run_test "4.2: 验证标准 CREATE VIEW 仍然严格" \
        "CREATE VIEW normal_view AS SELECT * FROM another_star_table;" \
        "FAIL" "does not exist"
        
    run_test "4.3: 验证会话状态安全 (关键测试)" \
        "CREATE FORCE VIEW syntax_error_view AS SELEC * FROM non_existent_table;" \
        "FAIL" "syntax error"
        
    run_test "4.4: 确认会话未被污染" \
        "SELECT * FROM a_fifth_non_existent_table;" \
        "FAIL" "does not exist"
)
total_exit_code=$?

# 步骤 3 & 4 由 trap 自动处理
if [ $total_exit_code -eq 0 ]; then
    print_msg "green" "\n🎉🎉🎉 恭喜您！所有测试用例均已通过！ 🎉🎉🎉"
else
    print_msg "red" "\n💥💥💥 部分测试用例失败，请检查上面的输出和日志文件 $PGXC_LOG 💥💥💥"
fi

exit $total_exit_code